beta1: 0.9
beta2: 0.95
clearml_project: GPT-QKV-Comparison
clearml_task: GPT-1.2B-QKV-24B
eval_interval: 500
eval_tokens: 10000000
grad_clip: 1.0
gradient_accumulation: 36
learning_rate: 6.0e-05
log_interval: 10
lr_scheduler: cosine
micro_batch_size: 2
min_lr: 6.0e-06
num_workers: 12
output_dir: ./outputs_1.2B_kqv
prefetch_factor: 6
save_interval: 1000
seed: 42
total_tokens: 10000000000
train_data_path: ./slimpajama_data/train
val_data_path: ./slimpajama_validation
warmup_steps: 1000
weight_decay: 0.1
