beta1: 0.9
beta2: 0.95
clearml_project: GPT-QKV-Comparison
clearml_task: GPT-300M-QKV-10B
eval_interval: 200
eval_tokens: 10000000
grad_clip: 1.0
gradient_accumulation: 24
learning_rate: 0.0002
log_interval: 10
lr_scheduler: cosine
micro_batch_size: 6
min_lr: 2.0e-05
num_workers: 16
output_dir: ./outputs_kqv
prefetch_factor: 6
save_interval: 1000
seed: 42
total_tokens: 10000000000
train_data_path: ./slimpajama_train
val_data_path: ./slimpajama_validation
warmup_steps: 500
weight_decay: 0.1
